#!/bin/bash
set -e
sed "s/RAILS_ENV/$RAILS_ENV/g" /etc/nginx/sites-enabled/webapp.conf.orig > /etc/nginx/sites-enabled/webapp.conf
if [[ ! -e /var/log/nginx/error.log ]]; then
	# The Nginx log forwarder might be sleeping and waiting
	# until the error log becomes available. We restart it in
	# 1 second so that it picks up the new log file quickly.
	(sleep 1 && sv restart /etc/service/nginx-log-forwarder)
fi
exec /usr/sbin/nginx
